[versions]
kotlin = "2.2.21"
dokka = "2.0.0"
shadow = "9.2.2"
slf4j = "2.1.0-alpha1"

binpack = "1.1.0"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }

[libraries]
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

binpack = { module = "net.ririfa:binpack", version.ref = "binpack" }